---
  Style/Documentation:
    Enabled: false

  Style/FrozenStringLiteralComment:
    Enabled: false

  Layout/SpaceAroundMethodCallOperator:
    Enabled: true

  Lint/RaiseException:
    Enabled: false

  Lint/StructNewOverride:
    Enabled: false

  Style/ExponentialNotation:
    Enabled: false

  Style/HashEachMethods:
    Enabled: false

  Style/HashTransformValues:
    Enabled: false

  Style/HashTransformKeys:
    Enabled: false

  Layout/EmptyLinesAroundAttributeAccessor:
    Enabled: false
  
  Lint/BinaryOperatorWithIdenticalOperands:
    Enabled: false
  
  Lint/DeprecatedOpenSSLConstant:
    Enabled: false
  
  Lint/DuplicateElsifCondition:
    Enabled: false
  
  Lint/DuplicateRescueException:
    Enabled: false
  
  Lint/EmptyConditionalBody:
    Enabled: false
  
  Lint/FloatComparison:
    Enabled: false
  
  Lint/MissingSuper:
    Enabled: false
  
  Lint/MixedRegexpCaptureTypes:
    Enabled: false
  
  Lint/OutOfRangeRegexpRef:
    Enabled: false
  
  Lint/SelfAssignment:
    Enabled: false
  
  Lint/TopLevelReturnWithArgument:
    Enabled: false
  
  Lint/UnreachableLoop:
    Enabled: false
  
  Style/AccessorGrouping:
    Enabled: false
  
  Style/ArrayCoercion:
    Enabled: false
  
  Style/BisectedAttrAccessor:
    Enabled: false
  
  Style/CaseLikeIf:
    Enabled: false
  
  Style/ExplicitBlockArgument:
    Enabled: false
  
  Style/GlobalStdStream:
    Enabled: false
  
  Style/HashAsLastArrayItem:
    Enabled: false
  
  Style/HashLikeCase:
    Enabled: false
  
  Style/OptionalBooleanParameter:
    Enabled: false
  
  Style/RedundantAssignment:
    Enabled: false
  
  Style/RedundantFetchBlock:
    Enabled: false
  
  Style/RedundantFileExtensionInRequire:
    Enabled: false
  
  Style/RedundantRegexpCharacterClass:
    Enabled: false
  
  Style/RedundantRegexpEscape:
    Enabled: false
  
  Style/SingleArgumentDig:
    Enabled: false
  
  Style/SlicingWithRange:
    Enabled: false
  
  Style/StringConcatenation:
    Enabled: false

  Layout/LineLength:
    Max: 110

  Metrics/MethodLength:
    Max: 20

  Metrics/BlockLength:
    Max: 50

  Metrics/AbcSize:
    Max: 30

  Metrics/CyclomaticComplexity:
    Max: 15

  Metrics/PerceivedComplexity:
    Max: 15
