source 'https://rubygems.org'

gem 'rspec', '3.7.0'
gem 'rspec-expectations', '3.7.0'
gem 'pry', '0.9.12.6'
gem 'pry-nav', '0.2.3'
# gem 'selenium-webdriver', '2.53'
gem 'selenium-webdriver', '3.14.1'
# gem 'activesupport', '4.1.11'
gem 'activesupport', '6.0.3'
gem 'cucumber'
gem 'rake', '12.3.1'
gem 'appium_lib', '10.6.0'
# gem 'appium_lib'
gem 'factory_girl', '~> 4.5'
gem 'minitest', '5.1'
# gem 'json', '1.8.6'
gem 'json', '2.1.0'
gem 'yaml'
gem 'selenium-cucumber'
gem 'browserstack-local'
