# config/cucumber.yml
##YAML Template
---
android: PLATFORM=android SCREENSHOT_PATH=screenshots/android/ -r features/support -r features/android -r features/common/step_definitions

report: -f html -o reports/report.html

